name: CI

on:
  push:
    branches: [ dev ]        # run CI when pushing to dev or main
  pull_request:
    branches: [ dev ]        # run CI when PR targets dev or main

jobs:
  shiny-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("shiny", "testthat", "ggplot2", "lubridate"))'

      - name: Run tests
        run: |
          R -e 'testthat::test_dir("Test")'
