name: R Shiny CI

on:
  push:
    branches:
      - dev
      - main
jobs:
  test-on-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("shiny", "testthat", "ggplot2", "lubridate"))'
      - name: List repo files
        run: ls -R
      # - name: Run tests
      #   run: |
      #     Rscript -e 'testthat::test_dir("Test/test-app.R")'
      - name: Check app.R runs without error
        run: |
          Rscript -e 'source("app.R"); message("app.R loaded successfully")

  test-on-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("shiny", "testthat", "ggplot2", "lubridate"))'
      - name: List repo files
        run: ls -R
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir('Test/test-app.R')'
      - name: Check app.R runs without error
        run: |
          Rscript -e 'source("app.R"); message("app.R loaded successfully")
